base_model: openaccess-ai-collective/tiny-mistral
dtype: bfloat16
experts:
- positive_prompts:
  - math
  source_model: openaccess-ai-collective/tiny-mistral
- positive_prompts:
  - science
  source_model: openaccess-ai-collective/tiny-mistral
- positive_prompts:
  - writing
  source_model: openaccess-ai-collective/tiny-mistral
- positive_prompts:
  - general
  source_model: openaccess-ai-collective/tiny-mistral
gate_mode: hidden
